### ISSUE TITLE
Issue regarding ImplicitMSALAuthenticationProvider

### ISSUE THREAD

**Issue by dumkanki** [microsoftgraph/msgraph-training-javascriptspa#12]
I have imported the ImplicitMSALAuthenticationProvider from the required module but again it is showing error.
Attempted import error: 'MSALAuthenticationProviderOptions' is not exported from '@microsoft/microsoft-graph-client' (imported as 'MicrosoftGraph').
Can anyone check this

**Comment by jasonjoh** [comment]
@dumkanki this sample doesn't use `import` statements, everything is just loaded in the browser via `<script>` tags. Can you provide more information about how you're seeing this error?
