### ISSUE TITLE
Not showing Signed in page

### ISSUE THREAD

**Issue by TK-Asaba** [microsoftgraph/msgraph-training-javascriptspa#13]
Hi,

I would like to have kind advise regarding the error which I`m facing.

According to the tutorial for SPA javascript program with MS graph,
I have completed by step  04-add-auth (implement sign-in) and when I tried to
login to MS account from sign-in on javascript app, UI didn`t change to indicate that I could signed-in.

In more detail about my error,  
  1) When I click "sign in", the pop-up window for MS login shown
  2) Signed-in to MS with my account and password
  3) Redirect to my localhost and new pop-up window shown
  4) UI not change to indicate that I am signed-in (Not shown with message of welcome and account info like screen on tutorial)  

I`m not sure what is the cause of this error and have no clue.
Appreciate for your help if you could.

**Comment by jasonjoh** [comment]
What browser or browsers are you using to test?

**Comment by TK-Asaba** [comment]
I tried on each browsers (Chrome, Edge, Firefox) but it resulted with same error (UI didn't change)

**Comment by jasonjoh** [comment]
I don't reproduce this issue. Have you debugged it in the browser dev tools? Do you see any errors, etc.?
