### ISSUE TITLE
Tutorial code for ui.js has a bug when referencing the account variable - it should be user

### ISSUE THREAD

**Issue by CameronDwyer** [microsoftgraph/msgraph-training-javascriptspa#16]
### Where did you get the code?

- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [X] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

The code in the tutorial (to copy/paste) when creating the ui.js file has a bug. This if statement should be `if (user)` not `if (account)`
![JS-SPA-02-if-user](https://user-images.githubusercontent.com/16345690/96336227-e5837280-10c9-11eb-9ae0-13d7a0eb26f1.jpg)

### To Reproduce

Follow the tutorial and copy/paste the code when creating ui.js

### Expected behavior

I expect the sign in to work and to see my account details, instead I get no welcome message and an error regarding no account in the javascript console.

The completed demo in this GitHub repo has the correct code, it's just the tutorial that is wrong.

**Comment by jasonjoh** [comment]
Thanks @CameronDwyer! I'll get this fixed.
