### ISSUE TITLE
Error getting events, empty JS object on page content

### ISSUE THREAD

**Issue by KaylaPratt** [microsoftgraph/msgraph-training-javascriptspa#29]
### Where did you get the code?

- [X] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [X] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

Alert text: "Error getting events." along with an empty JS object {}

No console errors are logged.

All the code is downloaded directly from this repo. I am signed into an Outlook account with several calendar events already added.

### To Reproduce

1. Click on "calendar" in nav bar

### Expected behavior

The table should display calendar events

### Desktop

- OS: Windows 7
- Browser: Chrome, Firefox
- Version: latest for both

**Comment by jasonjoh** [comment]
@KaylaPratt my apologies for the slow response. I've been on vacation over the holidays. Could you use dev tools in your browser to see what if any errors are logged in the console when you click on "Calendar"? Also you should be able to see the API call to Graph in the Network tab, it's possible that it's returning an error there.

**Comment by KaylaPratt** [comment]
Hey, no problem on the wait.

I went through the other issues logged and found out it was related to
another issue logged. Basically after logging in and fetching events,
hitting refresh will not return the results again. Didn't seem to be a
solution

**Comment by jasonjoh** [comment]
Check the changes here: https://github.com/microsoftgraph/msgraph-training-javascriptspa/pull/27/files
