### ISSUE TITLE
Feedback:  Explain why bluebird library is included in tutorial

### ISSUE THREAD

**Issue by oshihirii** [microsoftgraph/msgraph-training-javascriptspa#7]
I am trying to understand what is essential in getting an app that queries Microsoft Graph up and running.  I am following the tutorial here:

https://docs.microsoft.com/en-us/graph/tutorials/javascript?tutorial-step=1

In the HTML section it shows this:

```
 <!-- MSAL -->
 <script src="https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js"></script>
 <script src="https://alcdn.msftauth.net/lib/1.2.1/js/msal.js"
         integrity="sha384-9TV1245fz+BaI+VvCjMYL0YDMElLBwNS84v3mY57pXNOt6xcUYch2QLImaTahcOP"
         crossorigin="anonymous"></script>

 <!-- Graph SDK -->
 <script src="https://cdn.jsdelivr.net/npm/@microsoft/microsoft-graph-client/lib/graph-js-sdk.js"></script>
```
It goes on to say:

> This defines the basic layout of the app, including a navigation bar. It also adds the following:
> 
> Bootstrap and its supporting JavaScript
> FontAwesome
> Moment.js
> Microsoft Authentication Library for JavaScript (MSAL.js)
> Microsoft Graph JavaScript Client Library

but doesn't mention Bluebird.  

Why is bluebird included beneath the `MSAL` comment, and is Bluebird required for the app to function?

_Related research:_

_What is Bluebird?_  
A promise library for JavaScript.  

_Are promises supported in browsers?_
https://caniuse.com/#feat=promises

**Comment by jasonjoh** [comment]
Bluebird is there for MSAL. It's in their installation doc here: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-core#notes MSAL relies on Promise, so you need a polyfill for Promise if you're using a browser that doesn't natively support it. Bluebird is the one they show, but theoretically you could use any library that polyfills Promise.

Granted, they add it for IE support, so if you don't need to support IE you can probably remove it. I haven't tested that though.

**Comment by oshihirii** [comment]
Thank you for the information.
