### ISSUE TITLE
Understanding the difference between 'single', 'multitenant' and 'multitenant and personal ms accounts' options

### ISSUE THREAD

**Issue by oshihirii** [microsoftgraph/msgraph-training-javascriptspa#9]
Re:  https://docs.microsoft.com/en-us/graph/tutorials/javascript?tutorial-step=2

These are the options available:  

```
Supported account types
Who can use this application or access this API?

Accounts in this organizational directory only ([my organisation name] - Single tenant)
Accounts in any organizational directory (Any Azure AD directory - Multitenant)
Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)
```
The tutorial instructs to choose the last option and "locate the `Implicit` grant section and enable `Access tokens` and `ID tokens`".  

There is a link below the options area that says 'help me choose' which provides this information:

> **Understanding different account types**
> 
> **Accounts in this organizational directory only ([my organisation name] only - Single tenant)**
> All user and guest accounts in your directory can use your application or API.
>  
> _Use this option if your target audience is internal to your organization._
> 
> **Accounts in any organizational directory (Any Azure AD directory - Multitenant)**
> All users with a work or school account from Microsoft can use your application or API. This includes schools and businesses that use Office 365.
>  
> _Use this option if your target audience is business or educational customers and to enable multitenancy._
> 
> **Personal Microsoft accounts only**
> Personal accounts that are used to sign in to services like Xbox and Skype.
>  
> _Use this option to target the widest set of Microsoft identities._
> 
> 
> Due to temporary differences in functionality, you may see errors if you attempt to switch between supported audiences after registering the application.

The way I interpret 'single tenant' therefore is:

>  Any user in my organisation account can login and use the app, everyone else can't.    

When I register an app and select the 'single tenant' option and try and login (with the only user account in the organisation account), I get this error:

> ServerError: AADSTS50194: Application 'application-id-here'(app-name-here) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

So the desired behaviour is that only users within the organisation can access the app  

Why isn't it working and how can I get it working?

Thank You.    

Edit - related research:

https://github.com/MicrosoftDocs/azure-docs/issues/19646

https://github.com/MicrosoftDocs/azure-docs/issues/19346

https://docs.microsoft.com/en-us/azure/active-directory/develop/supported-accounts-validation

https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant#update-registration-to-be-multi-tenant

Search results for `/common` in MSAL repo:

https://github.com/AzureAD/microsoft-authentication-library-for-js/search?q=%2Fcommon&unscoped_q=%2Fcommon

**Comment by jasonjoh** [comment]
Your authorization request can't use the `/common` segment unless it is multitenant. For single tenant apps, you replace that segment with the specified tenant ID. See https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#send-the-sign-in-request

> The `{tenant}` value in the path of the request can be used to control who can sign into the application. The allowed values are `common`, `organizations`, `consumers`, and tenant identifiers. For more detail, see protocol basics.

For this app, you need to set `authority` in the msalConfig's `auth` object. See https://docs.microsoft.com/azure/active-directory/develop/msal-js-initializing-client-applications#configuration-options

**Comment by oshihirii** [comment]
Thank you very much.  

For others needing to know where tenant id is, see these links:

https://docs.microsoft.com/en-us/onedrive/find-your-office-365-tenant-id  
https://o365hq.com/faq/how-to-find-your-office-365-tenant-id  

And to be specific, the following worked for me:
```
const msalConfig = {
    auth: {
        clientId: "your-application-client-id",
        redirectUri: "http://localhost:8080",
        authority: "https://login.microsoftonline.com/your-tenant-id"  // <---- added this
    },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false,
    forceRefresh: false
  }
};
```
